version: '3'
services:
  rust:
    build: rust
    hostname: rust
    container_name: dev
    volumes:
      - rust-v:/prj
    working_dir: /prj
  
  node:
    build: node
    hostname: node
    container_name: dev
    volumes:
      - node-v:/prj
    working_dir: /prj

volumes:
  rust-v:
    driver: local
  node-v:
    driver: local